### ISSUE TITLE
Exception : unsupported field type : option

### ISSUE THREAD

**Issue by dt-lizac** [rcarz/jira-client#123]
Hi,

trying to use custom fields, I encounter the following issue : 
For a "Select List (single choice)" type of field, I get the following exception when trying to create an issue : 
Exception: java.lang.UnsupportedOperationException: option is not a supported field type
                at net.rcarz.jiraclient.Field.toJson(Field.java:655)
                at net.rcarz.jiraclient.Issue$FluentCreate.executeCreate(Issue.java:104)
                at net.rcarz.jiraclient.Issue$FluentCreate.execute(Issue.java:59)
 
I'm using JIRA v7.1.0-OD-05-006

**Comment by sv-sclo** [comment]
Hi,

it seems that there is a new field-type "option" in JIRA-7 for some fields. While it worked on JIRA-6, the same fields didn't work on JIRA-7.

The solution seems to be very simple, just add the new type and treat it like a string field (which it was before in JIRA-6):

In Field.toJson() (Line 642), write

`} else if (m.type.equals("string") || (m.type.equals("securitylevel") || (m.type.equals("option")))) {`

instead of

`} else if (m.type.equals("string") || (m.type.equals("securitylevel"))) {`

**Comment by rcarz** [comment]
Hi, this should be fixed with #154.
